CREATE SCHEMA CHRISTINE;

CREATE SEQUENCE CHRISTINE.GENERIC_SEQ
START WITH 50002
INCREMENT BY 1;

CREATE TABLE CHRISTINE.CURRENCY_TYPE
(
CURRENCY_TYPE_ID NUMBER NOT NULL,
MNEMONIC VARCHAR(100) NOT NULL UNIQUE,
CURRENCY_TYPE_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY(CURRENCY_TYPE_ID)
);


CREATE TABLE CHRISTINE.ACCOUNT_TYPE
(
ACCOUNT_TYPE_ID NUMBER NOT NULL,
MNEMONIC VARCHAR(100) NOT NULL,
CURRENCY_TYPE_NAME VARCHAR(255) NOT NULL,
CREATION_DATE DATE NOT NULL,
PRIMARY KEY(ACCOUNT_TYPE_ID)
);

CREATE TABLE CHRISTINE.CURRENCY_TX
(
TX_ID NUMBER NOT NULL,
CURRENCY_TYPE_ID NUMBER NOT NULL,
MEMBER_ID NUMBER NOT NULL,
AMOUNT NUMBER NOT NULL,
TX_DATE DATE NOT NULL,
PRIMARY KEY (TX_ID),
CONSTRAINT FK_CURRENCY_TYPE_ID FOREIGN KEY (CURRENCY_TYPE_ID) REFERENCES CHRISTINE.CURRENCY_TYPE (CURRENCY_TYPE_ID)

);

CREATE TABLE CHRISTINE.ACCOUNT_TX_DETAILS
(
ACCOUNT_TX_DETAILS_ID NUMBER NOT NULL,
TX_ID NUMBER NOT NULL,
PARTNER_NAME VARCHAR(255) NOT NULL,
AMOUNT NUMBER NOT NULL,
NUMBER_OF_ITEMS DATE NOT NULL,
PRIMARY KEY (ACCOUNT_TX_DETAILS_ID),
CONSTRAINT FK_ACCOUNT_TX_ID FOREIGN KEY (TX_ID) REFERENCES CHRISTINE.ACCOUNT_TX (TX_ID)

);

CREATE TABLE CHRISTINE.ACCOUNT_TX
(
TX_ID NUMBER NOT NULL,
ACCOUNT_TYPE_ID NUMBER NOT NULL,
MEMBER_ID NUMBER NOT NULL,
AMOUNT NUMBER NOT NULL,
TX_DATE DATE NOT NULL,
PRIMARY KEY (TX_ID),
CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES CHRISTINE.ACCOUNT_TYPE (ACCOUNT_TYPE_ID)

);

CREATE TABLE CHRISTINE.CURRENCY_TX_DETAILS
(
CURRENCY_TX_DETAILS_ID NUMBER NOT NULL,
TX_ID NUMBER NOT NULL,
PARTNER_NAME VARCHAR(255) NOT NULL,
AMOUNT NUMBER NOT NULL,
NUMBER_OF_ITEMS DATE NOT NULL,
PRIMARY KEY (CURRENCY_TX_DETAILS_ID),
CONSTRAINT FK_CURRENCY_TX_ID FOREIGN KEY (TX_ID) REFERENCES CHRISTINE.CURRENCY_TX (TX_ID)

);