Insert into CHRISTINE.CURRENCY (CURRENCY_ID,CURRENCY_DESC,CURRENCY_TYPE) values (1,'South African Rand','R');
Insert into CHRISTINE.CURRENCY (CURRENCY_ID,CURRENCY_DESC,CURRENCY_TYPE) values (2,'Discovery Miles','Miles');
Insert into CHRISTINE.CURRENCY (CURRENCY_ID,CURRENCY_DESC,CURRENCY_TYPE) values (3,'Namibian Dollar','N$');

INSERT INTO "CHRISTINE"."PARTNER" (PARTNER_ID, PARTNER_DESC, PARTNER_TYPE) VALUES ('1', 'Pick a Pay Clothing', 'Temporary')
INSERT INTO "CHRISTINE"."PARTNER" (PARTNER_ID, PARTNER_DESC, PARTNER_TYPE) VALUES ('2', 'Checkers Hyper', 'Permanent')
INSERT INTO "CHRISTINE"."PARTNER" (PARTNER_ID, PARTNER_DESC, PARTNER_TYPE) VALUES ('3', 'Takealot', 'Permanent')

INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION" (MEMBER_ACC_TRANS_ID, MEMBER_ACC_TRANS_DESC, MEMBER_ACC_TRANS_DATE) VALUES ('1', 'Rewards', TO_DATE('2021-10-03 13:44:54', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION" (MEMBER_ACC_TRANS_ID, MEMBER_ACC_TRANS_DESC, MEMBER_ACC_TRANS_DATE) VALUES ('2', 'Rewards', TO_DATE('2021-10-01 13:45:11', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION" (MEMBER_ACC_TRANS_ID, MEMBER_ACC_TRANS_DESC, MEMBER_ACC_TRANS_DATE) VALUES ('3', 'Rewards', TO_DATE('2021-10-05 13:45:21', 'YYYY-MM-DD HH24:MI:SS'))

INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION" (MEMBER_ACC_TRANS_ID, MEMBER_ACC_TRANS_DESC, MEMBER_ACC_TRANS_DATE) VALUES ('1', 'Rewards', TO_DATE('2021-10-03 13:44:54', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION" (MEMBER_ACC_TRANS_ID, MEMBER_ACC_TRANS_DESC, MEMBER_ACC_TRANS_DATE) VALUES ('2', 'Rewards', TO_DATE('2021-10-01 13:45:11', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION" (MEMBER_ACC_TRANS_ID, MEMBER_ACC_TRANS_DESC, MEMBER_ACC_TRANS_DATE) VALUES ('3', 'Rewards', TO_DATE('2021-10-05 13:45:21', 'YYYY-MM-DD HH24:MI:SS'))

INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION_DETAILS" (MEMBER_ACC_TRANS_DET_ID, MEMBER_ACC_TRANS_DET_DESC, MEMBER_ACC_TRANS_ID, MEMBER_ACC_ID, PARTNER_ID, CURRENCY_ID) VALUES ('1', 'Subtract Miles', '1', '1', '1', '1')
INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION_DETAILS" (MEMBER_ACC_TRANS_DET_ID, MEMBER_ACC_TRANS_DET_DESC, MEMBER_ACC_TRANS_ID, MEMBER_ACC_ID, PARTNER_ID, CURRENCY_ID) VALUES ('2', 'Add Miles', '2', '2', '2', '2')
INSERT INTO "CHRISTINE"."MEMBER_ACC_TRANSACTION_DETAILS" (MEMBER_ACC_TRANS_DET_ID, MEMBER_ACC_TRANS_DET_DESC, MEMBER_ACC_TRANS_ID, MEMBER_ACC_ID, PARTNER_ID, CURRENCY_ID) VALUES ('3', 'Add Miles', '3', '3', '3', '3')

INSERT INTO "CHRISTINE"."MEMBER" (MEMBER_ID, MEMBER_FNAME, MEMBER_LNAME, MEMBER_DESC, MEMBER_ACC_TRANS_DET_ID, MEMBER_ACC_ID) VALUES ('1', 'Christine', 'Abreu de Jesus', 'Active Member', '1', '1')
INSERT INTO "CHRISTINE"."MEMBER" (MEMBER_ID, MEMBER_FNAME, MEMBER_LNAME, MEMBER_DESC, MEMBER_ACC_TRANS_DET_ID, MEMBER_ACC_ID) VALUES ('2', 'Pieter', 'Abreu de Jesus', 'Active Member', '2', '2')
INSERT INTO "CHRISTINE"."MEMBER" (MEMBER_ID, MEMBER_FNAME, MEMBER_LNAME, MEMBER_DESC, MEMBER_ACC_TRANS_DET_ID, MEMBER_ACC_ID) VALUES ('3', 'Chantelle', 'Muller', 'Active Member', '3', '3')

