
  CREATE TABLE "CHRISTINE"."CURRENCY"
   (	"CURRENCY_ID" NUMBER NOT NULL ENABLE,
	"CURRENCY_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CURRENCY_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "CURRENCY_PK" PRIMARY KEY ("CURRENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "CHRISTINE"."PARTNER"
   (	"PARTNER_ID" NUMBER(*,0) NOT NULL ENABLE,
	"PARTNER_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"PARTNER_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "PARTNER_PK" PRIMARY KEY ("PARTNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE TABLE "CHRISTINE"."MEMBER_ACCOUNT"
   (	"MEMBER_ACC_ID" NUMBER(*,0) NOT NULL ENABLE,
	"MEMBER_ACC_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"MEMBER_ACC_LIMIT" NUMBER NOT NULL ENABLE,
	"MEMBER_AMOUNT" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "MEMBER_ACCOUNT_PK" PRIMARY KEY ("MEMBER_ACC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE TABLE "CHRISTINE"."MEMBER_ACC_TRANSACTION"
   (	"MEMBER_ACC_TRANS_ID" NUMBER NOT NULL ENABLE,
	"MEMBER_ACC_TRANS_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"MEMBER_ACC_TRANS_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "MEMBER_ACC_TRANSACTION_PK" PRIMARY KEY ("MEMBER_ACC_TRANS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "CHRISTINE"."MEMBER_ACC_TRANSACTION_DETAILS"
   (	"MEMBER_ACC_TRANS_DET_ID" NUMBER NOT NULL ENABLE,
	"MEMBER_ACC_TRANS_DET_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"MEMBER_ACC_TRANS_ID" NUMBER NOT NULL ENABLE,
	"MEMBER_ACC_ID" NUMBER NOT NULL ENABLE,
	"PARTNER_ID" NUMBER NOT NULL ENABLE,
	"CURRENCY_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("MEMBER_ACC_TRANS_DET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "CURRENCY_ID" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "CHRISTINE"."CURRENCY" ("CURRENCY_ID") ENABLE,
	 CONSTRAINT "PARTNER_ID" FOREIGN KEY ("PARTNER_ID")
	  REFERENCES "CHRISTINE"."PARTNER" ("PARTNER_ID") ENABLE,
	 CONSTRAINT "MEMBER_ACCOUNT_ID" FOREIGN KEY ("MEMBER_ACC_ID")
	  REFERENCES "CHRISTINE"."MEMBER_ACCOUNT" ("MEMBER_ACC_ID") ENABLE,
	 CONSTRAINT "MEMBER_ACC_TRANS_ID" FOREIGN KEY ("MEMBER_ACC_TRANS_ID")
	  REFERENCES "CHRISTINE"."MEMBER_ACC_TRANSACTION" ("MEMBER_ACC_TRANS_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE TABLE "CHRISTINE"."MEMBER"
   (	"MEMBER_ID" NUMBER NOT NULL ENABLE,
	"MEMBER_FNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"MEMBER_LNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"MEMBER_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"MEMBER_ACC_TRANS_DET_ID" NUMBER NOT NULL ENABLE,
	"MEMBER_ACC_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "MEMBER_ACC_TRANS_DET_ID" FOREIGN KEY ("MEMBER_ACC_TRANS_DET_ID")
	  REFERENCES "CHRISTINE"."MEMBER_ACC_TRANSACTION_DETAILS" ("MEMBER_ACC_TRANS_DET_ID") ENABLE,
	 CONSTRAINT "MEMBER_ACC_ID" FOREIGN KEY ("MEMBER_ACC_ID")
	  REFERENCES "CHRISTINE"."MEMBER_ACCOUNT" ("MEMBER_ACC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
